"""Add Site, GlobalConfig, and AdminUser models

Revision ID: d717d71ba41f
Revises: 
Create Date: 2025-12-09 09:07:03.021432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd717d71ba41f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('global_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proxy_subdomains', sa.Boolean(), nullable=False),
    sa.Column('proxy_external_domains', sa.Boolean(), nullable=False),
    sa.Column('rewrite_js_redirects', sa.Boolean(), nullable=False),
    sa.Column('remove_ads', sa.Boolean(), nullable=False),
    sa.Column('inject_ads', sa.Boolean(), nullable=False),
    sa.Column('remove_analytics', sa.Boolean(), nullable=False),
    sa.Column('media_policy', sa.String(), nullable=False),
    sa.Column('session_mode', sa.String(), nullable=False),
    sa.Column('custom_ad_html', sa.Text(), nullable=True),
    sa.Column('custom_tracker_js', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mirror_root', sa.String(), nullable=False),
    sa.Column('source_root', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('proxy_subdomains', sa.Boolean(), nullable=True),
    sa.Column('proxy_external_domains', sa.Boolean(), nullable=True),
    sa.Column('rewrite_js_redirects', sa.Boolean(), nullable=True),
    sa.Column('remove_ads', sa.Boolean(), nullable=True),
    sa.Column('inject_ads', sa.Boolean(), nullable=True),
    sa.Column('remove_analytics', sa.Boolean(), nullable=True),
    sa.Column('media_policy', sa.String(), nullable=True),
    sa.Column('session_mode', sa.String(), nullable=True),
    sa.Column('custom_ad_html', sa.Text(), nullable=True),
    sa.Column('custom_tracker_js', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_mirror_root'), 'sites', ['mirror_root'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_mirror_root'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('global_config')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
