"""Add cookie_jar table for Phase 8

Revision ID: ea2bb0e2f943
Revises: d717d71ba41f
Create Date: 2025-12-09 15:54:59.786720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2bb0e2f943'
down_revision: Union[str, Sequence[str], None] = 'd717d71ba41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookie_jars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('origin_host', sa.String(length=255), nullable=False),
    sa.Column('cookie_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cookie_jar_lookup', 'cookie_jars', ['site_id', 'session_id', 'origin_host'], unique=False)
    op.create_index(op.f('ix_cookie_jars_id'), 'cookie_jars', ['id'], unique=False)
    op.create_index(op.f('ix_cookie_jars_origin_host'), 'cookie_jars', ['origin_host'], unique=False)
    op.create_index(op.f('ix_cookie_jars_session_id'), 'cookie_jars', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cookie_jars_session_id'), table_name='cookie_jars')
    op.drop_index(op.f('ix_cookie_jars_origin_host'), table_name='cookie_jars')
    op.drop_index(op.f('ix_cookie_jars_id'), table_name='cookie_jars')
    op.drop_index('idx_cookie_jar_lookup', table_name='cookie_jars')
    op.drop_table('cookie_jars')
    # ### end Alembic commands ###
